### ISSUE TITLE
TerraForged Compatibility 

### ISSUE THREAD

**Issue by disastercube** [Cryptic-Mushroom/The-Midnight#408] opened 2020-05-27 21:24 UTC
Midnight mod 1.15.2  0.5.7 -3

I've made several worlds with TerraForged world generation and none of them had a red heap. 
Every single world when performing the command "/locate midnight:entrance_rift" gives a warning
"Could not find that structure nearby", it works fine with the default generation though. I do not know if this is a compatibility issue with midnight or terraforged mod or just me being blind and missing something in the config file.

![2020-05-27_23 23 30](https://user-images.githubusercontent.com/62697421/83073669-19a1bc80-a071-11ea-977c-d30701ce76d9.png)

**Comment by nonrumor** [comment] 2020-05-27 22:56
I've been able to find them. Which version of terrafoged are you using? and what are you settings for terraforged?

**Comment by Jonathing** [comment] 2020-05-28 02:41
Duplicate of #406. Title changed accordingly.

**Closed by Jonathing** 2020-05-28 02:41 UTC

**Comment by disastercube** [comment] 2020-05-28 08:35
Settings are default.
Terraforged: 1.15.2  0.0.14
