### ISSUE TITLE
Portals fail to generate on a dedicated server, but do on single player

### ISSUE THREAD

**Issue by littlett98** [Cryptic-Mushroom/The-Midnight#282] opened 2019-08-21 16:46 UTC
No rifts spawn on multiplayer server.
I can find rifts on a new single player world.
The multiplayer server existed before we added the mod.
We can spawn in all elements of the midnight using creative on our server.
https://pastebin.com/N9cdCj4J

**Comment by ProsperCraft** [comment] 2019-08-21 20:24
I can confirm we are seeing this on The Adventures of Halk server as well.

**Comment by SmellyModder** [comment] 2019-08-21 23:48
Every modded entity throws the 'No data fixer registered for entity" error

**Comment by ProsperCraft** [comment] 2019-08-21 23:51
I think the title needs to be changed to 
"Portals fail to generate on a dedicated server, but do on single player"
themidnight-0.4.3

**Comment by littlett98** [comment] 2019-08-22 02:00
My bad, I think "Portals fail to generate on a dedicated server, but do on single player" is much more accurate. Any way to change the title?

**Comment by SmellyModder** [comment] 2019-08-22 02:11
I'll do it

**Comment by gegy1000** [comment] 2019-08-22 05:06
@Corail31 has been looking into it -- it seems it's related to the gamerule

**Comment by littlett98** [comment] 2019-08-22 08:58
Is that something I misconfigured? I have only messed with randomtickspeed (it is set to default right now) and difficulty (at normal right now)

**Comment by Corail31** [comment] 2019-08-22 13:17
@littlett98 it's not a misconfiguration, the custom gamerule doesn't work on server, except when in workspace.
If this line is removed, it works again.
[Code Link](https://github.com/Cryptic-Mushroom/The-Midnight/blob/1.14.4-dev/src/main/java/com/mushroom/midnight/common/world/RiftSpawnHandler.java#L54)

**Comment by gegy1000** [comment] 2019-08-24 17:47
I believe that this is caused by gamerule initializing to false when on a previously existing world (possibly includes servers on new worlds too?)
In any case, this should be fixed in https://github.com/Cryptic-Mushroom/The-Midnight/commit/89d7222e39bc829a70075f8919fec1d5f92e8eff

**Closed by gegy1000** 2019-08-24 17:47 UTC
