### ISSUE TITLE
Crashed whenever i enter the portal, now my world cant be opened as it always crashes.

### ISSUE THREAD

**Issue by onetann** [Cryptic-Mushroom/The-Midnight#234] opened 2019-05-27 12:59 UTC
my forge version is 2772. 1.12.2 help pls
https://pastebin.com/raCp5tuq
Edit by Corail31 : you should learn how to use pastebin

**Comment by Corail31** [comment] 2019-05-27 14:41
https://www.minecraftforge.net/forum/topic/67098-1122-forge-crashing-at-world-loading-single-player/
```
Posted October 31, 2018
FIXED IT!

I had to update optifine to latest version. Found out i did not have the latest update.
```

**Comment by Corail31** [comment] 2019-05-30 12:48
@onetann is it solved ?

**Comment by Jonathing** [comment] 2019-06-26 04:59
I'm surprised this issue is still open. If I can't find a cause for it, I'm closing it.

**Comment by Jonathing** [comment] 2019-06-26 05:18
I'm closing this issue for the following reasons:
- In the Optifine 1.12.2 changelog from E2 to E3, forge compatibility was added.
- The issue is too vague. There's no extra info on how to reproduce the issue.

If somehow this issue persists with the latest issue of OptiFine, feel free to @ me and I'll take a look.

**Closed by Jonathing** 2019-06-26 05:18 UTC
