### ISSUE TITLE
spamming logs and potential crash after

### ISSUE THREAD

**Issue by lampyr** [Cryptic-Mushroom/The-Midnight#207] opened 2019-03-03 03:34 UTC
hi i have a very lots of spam in the log when i instal your mod:

[02:25:01] [Thread-32/ERROR] [net.minecraft.client.audio.SoundManager]: Error in class 'SourceLWJGL OpenAL'
[02:25:01] [Thread-32/ERROR] [net.minecraft.client.audio.SoundManager]: Invalid enumerated parameter value.

and this crash:

Time: 2019-03-03 02:38:29 CET
Description: Exception ticking world

java.lang.IllegalStateException: TickNextTick list out of synch
    at net.minecraft.world.WorldServer.tickUpdates(WorldServer.java:691)
    at net.minecraft.world.WorldServer.tick(WorldServer.java:223)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)

thank you in advance if you can help me.

**Comment by Jonathing** [comment] 2019-06-26 05:41
related to issue #235. I can't figure out what the cause is.

**Comment by ShowerChunk5** [comment] 2019-07-04 23:26
I have the same problem rn. Do you use MultiMC? I'm curious.

**Comment by Corail31** [comment] 2019-07-22 02:14
i close it as it's a dupe of #245 and it contains less infos.

**Closed by Corail31** 2019-07-22 02:14 UTC
Labels: bug
