### ISSUE TITLE
Incompatibility when using Better Foliage & Optifine

### ISSUE THREAD

**Issue by RyanCR03** [Cryptic-Mushroom/The-Midnight#37] opened 2018-10-21 03:52 UTC
Nightshrooms Crystal Flowers Dewshrooms ViridShrooms and Lumen Buds All have square missing textures that look like this:
![2018-10-20_22 50 42](https://user-images.githubusercontent.com/32957560/47262933-d5286500-d4ba-11e8-81aa-b12d6a689c9e.png)

**Comment by RyanCR03** [comment] 2018-10-21 15:48
I have a lot of mods it would be hard to name them all

**Comment by RyanCR03** [comment] 2018-10-21 15:49
What mods conflict with it?

**Comment by RyanCR03** [comment] 2018-10-21 17:33
Ok, I will try that


On Oct 21, 2018 12:27 PM, "Terenx" <notifications@github.com> wrote:

Could be a download error, you might not have downloaded the textures, try
redownloading the mod

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Cryptic-Mushroom/Midnight/issues/37#issuecomment-431687471>,
or mute the thread

**Comment by RyanCR03** [comment] 2018-10-21 17:43
Didn't work :(

**Comment by Terenx** [comment] 2018-10-21 17:48
Maybe remove other mods one at a time and make test worlds to see if your textures come back, and find which mod it is, try removing optifine first if you have it

**Comment by gegy1000** [comment] 2018-10-21 18:48
A log file would also be useful. :)

**Comment by ItzDennisz** [comment] 2018-10-22 20:22
a log file. you know, a magical file that contains details on what could possibly cause the game to behave this way so that they can actually solve the problem..

**Comment by RyanCR03** [comment] 2018-10-23 04:05
Where do I find them?

**Comment by wenlfs** [comment] 2018-10-27 23:36
I having the same issue. I did remove some mod that were updated yesterday because it wasn't happening and without Better Foliage it works fine.
Do you use Better Foliage too?

**Comment by RyanCR03** [comment] 2018-10-28 00:30
Yes

On Oct 27, 2018 6:36 PM, "wenlfs" <notifications@github.com> wrote:

I having the same issue. I did remove some mod that were updated yesterday
because it wasn't happening and without Better Foliage it works fine.
Do you use Better Foliage too?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Cryptic-Mushroom/Midnight/issues/37#issuecomment-433663994>,
or mute the thread

**Comment by wenlfs** [comment] 2018-10-28 19:42
Seems that the issue isn't only due Better Foliage, I'm running it with Better Foliage and it works right when without Optifine. So, If you use both mods the issue happens and if you use one of then it doesn't happen.

**Comment by RyanCR03** [comment] 2018-10-28 23:15
I don't use optifine

**Comment by Terenx** [comment] 2018-11-01 13:38
well just dont use optifine with most mods unless they say optifine compatible, I remember playing this one mod with optifine and it wouldn't let me open chests, heck, opening an ender chest just immediately crashes the game, I had to use hoppers to get dungeon loot

**Comment by wargex** [comment] 2018-12-07 17:14
Turning off optifine has no effect on the missing textures. I'm not sure why there are missing textures wrapping these blocks. If you look inside the missing textures, there are textures, they actually load in just fine, the bug isn't that they're missing, just that they're being wrapped like they are missing. 
Turning off Better Foliage was the only thing I could do to remove the missing wraps, and that's using all versions of both Foliage, and Forgelin, I was through. However I haven't tested all of the versions of optifine either. But I've already made it work perfectly with optifine, so I'm not going to do that.

**Comment by RyanCR03** [comment] 2018-12-07 20:03
Ok thanks

**Comment by Andromander** [comment] 2018-12-08 23:15
This is an issue on BetterFoliage's end due to rendering hacks.

**Comment by InsomniaKitten** [comment] 2018-12-08 23:20
To be more clear, the issue is that Better Foliage's hooks have no support for models that render in multiple layers (e.g. `forge:multi-layer`). This is something that can only be fixed on Better Foliage's end, and the only "solution" on this end would be to avoid using `forge:multi-layer`, which of course isn't ideal. Also see: https://github.com/Chisel-Team/Chisel/issues/716

**Comment by five0five** [comment] 2019-03-07 02:29
As this is not an issue on our end, should it be closed?

**Closed** 2019-08-09 15:22 UTC
Labels: bug
