### ISSUE TITLE
Some midnight planks aren't tagged as #minecraft:planks

### ISSUE THREAD

**Issue by sargunv** [Cryptic-Mushroom/The-Midnight#394] opened 2020-05-01 09:39 UTC
This prevents some other mods from treating them as planks (for example, Natural Progression changing all plank recipes). It's easy to resolve on the user end with a data pack so not sure if it's intentional, if so no problem!

I fixed it on my end with the following in data/minecraft/tags/{blocks|items}/planks.json

```
{
    "replace": false,
    "values": [
        "#midnight:planks"
    ]
}
```

#### Environment
- Midnight: 0.5.7-3
- Forge: 31.1.51 for MC 1.15.2

**Comment by RedGalaxySW** [comment] 2020-05-01 16:03
This issue is somewhat duplicate of #388, so I'll close this one and refer you to #388...

**Closed by RedGalaxySW** 2020-05-01 16:03 UTC
