### ISSUE TITLE
Textures not rendering with shaders

### ISSUE THREAD

**Issue by Maxwelt44** [Cryptic-Mushroom/The-Midnight#335] opened 2020-01-06 15:53 UTC
I am currently using Sildur's vibrant but I also tested other shaders and it appears that while in the dimension the textures are either not rendering or theres is just some weird shaders effects. Removing shaders fix the issue, but it would be nice to have the mod compatible with shaders.
![2020-01-06_10 44 47](https://user-images.githubusercontent.com/59571739/71829450-ad4b0000-3072-11ea-90e8-d23d3edb28c7.png)

**Comment by Maxwelt44** [comment] 2020-01-06 20:03
I also found out that while a portal is being spawned in the overworld, all the entity are glowing white with a shaders from certain angle and distance.
![2020-01-06_14 55 08](https://user-images.githubusercontent.com/59571739/71844791-fad86480-3094-11ea-9eb4-96b5e8ab2263.png)
![2020-01-06_14 55 04](https://user-images.githubusercontent.com/59571739/71844793-fb70fb00-3094-11ea-89b6-ab59ea9ccd2c.png)

**Comment by canteloupeSamurai** [comment] 2020-01-10 01:02
Have the same problem.

**Comment by Jonathing** [comment] 2020-03-26 15:23
Duplicate of issue #337

**Closed by Jonathing** 2020-03-26 15:23 UTC
Labels: 1.14.4, Duplicate, Mod Compatability
