### ISSUE TITLE
[MC VERSION] Bug Report Game crashes on launch

### ISSUE THREAD

**Issue by crysins** [Cryptic-Mushroom/The-Midnight#464] opened 2021-02-19 20:02 UTC
The game constantly crashing on launch and cannot find a solution. The mod is in a mod pack that I have created. I assume for now it has to do with my memory and that it cannot run all the mods because I launched the game in a separate mod pack with only the midnight mod in it and it worked fine. However the mod pack works fine without the midnight mod. Also, the mod still crashed even when I removed other mods in the mod pack to reduce the memory usage
![report](https://user-images.githubusercontent.com/79334981/108555395-51cae880-72ed-11eb-9cec-74fa15a84768.PNG)
.

**Comment by Jonathing** [comment] 2021-02-19 20:41
Looks like you're running on 1.12.2. Unfortunately, we don't really support 1.12.2 issues anymore because the 1.12.2 version is severely outdated and most of its bugs have been fixed in future releases.

I don't know what exactly the issue is because you haven't sent any crash report, but the most common one is that another mod is already using the dimension ID -23. Please review your config files to make sure there aren't any issues in that regard.

**Closed by Jonathing** 2021-02-19 20:41 UTC
Labels: Pre-rewrite
