### ISSUE TITLE
Java 9+

### ISSUE THREAD

**Issue by FoxShadew** [Cryptic-Mushroom/The-Midnight#446] opened 2020-12-05 15:07 UTC
Opening this issue because of #445 lead to more discussion about Java 9+ rather than the actual issue proposed in #445. Right now the Midnight does not completely support Java 9+ because of reflection issues (changing JVM flags might make it supported but Java 9+ wasn't taken into account yet by the devs).

If you have issues up to Java 11, try adding these JVM flags:
```
--add-opens java.base/jdk.internal.reflect=ALL-UNNAMED
```

**Comment by tkreind** [comment] 2021-01-02 05:08
This is an issue when running natively on Apple Silicon which only has java 11+ built. I got the following crash, this was the only mod causing issues for me playing Valhesia.

`[02Jan2021 05:02:21.971] [modloading-worker-2/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/]: Exception caught during firing event: null
	Index: 1
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$2302/0x0000000800e36440@16771ab7
		2: net.minecraftforge.eventbus.EventBus$$Lambda$2302/0x0000000800e36440@1b016cee
java.lang.ExceptionInInitializerError
	at com.mushroom.midnight.client.ClientProxy.setup(ClientProxy.java:53)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106)
	at java.base/java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
	at java.base/java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112)
	at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:135)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.RuntimeException: Can't add enum
	at com.mushroom.midnight.common.util.EnumUtil.addEnum(EnumUtil.java:139)
	at com.mushroom.midnight.common.recipe.MidnightRecipeBookCategories.<clinit>(MidnightRecipeBookCategories.java:11)
	... 19 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make public java.lang.Object jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(java.lang.Object[]) throws java.lang.InstantiationException,java.lang.IllegalArgumentException,java.lang.reflect.InvocationTargetException accessible: module java.base does not "opens jdk.internal.reflect" to unnamed module @2994dee5
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:340)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:280)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:198)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:192)
	at com.mushroom.midnight.common.util.EnumUtil.buildEnum(EnumUtil.java:98)
	at com.mushroom.midnight.common.util.EnumUtil.addEnum(EnumUtil.java:137)
	... 20 more

[02Jan2021 05:02:21.972] [modloading-worker-2/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Caught exception during event FMLCommonSetupEvent dispatch for modid midnight
java.lang.ExceptionInInitializerError: null
	at com.mushroom.midnight.client.ClientProxy.setup(ClientProxy.java:53) ~[?:0.5.11]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-2.2.1-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-2.2.1-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.1-service.jar:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106) ~[?:31.2]
	at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65) ~[?:?]
	at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65) ~[?:?]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) ~[?:?]
	at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:135) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) [?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) [?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) [?:?]
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290) [?:?]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
Caused by: java.lang.RuntimeException: Can't add enum
	at com.mushroom.midnight.common.util.EnumUtil.addEnum(EnumUtil.java:139) ~[?:0.5.11]
	at com.mushroom.midnight.common.recipe.MidnightRecipeBookCategories.<clinit>(MidnightRecipeBookCategories.java:11) ~[?:0.5.11]
	... 19 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make public java.lang.Object jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(java.lang.Object[]) throws java.lang.InstantiationException,java.lang.IllegalArgumentException,java.lang.reflect.InvocationTargetException accessible: module java.base does not "opens jdk.internal.reflect" to unnamed module @2994dee5
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:340) ~[?:?]
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:280) ~[?:?]
	at java.lang.reflect.Method.checkCanSetAccessible(Method.java:198) ~[?:?]
	at java.lang.reflect.Method.setAccessible(Method.java:192) ~[?:?]
	at com.mushroom.midnight.common.util.EnumUtil.buildEnum(EnumUtil.java:98) ~[?:0.5.11]
	at com.mushroom.midnight.common.util.EnumUtil.addEnum(EnumUtil.java:137) ~[?:0.5.11]
	at com.mushroom.midnight.common.recipe.MidnightRecipeBookCategories.<clinit>(MidnightRecipeBookCategories.java:11) ~[?:0.5.11]
	... 19 more`

**Comment by Jonathing** [comment] 2021-01-02 06:35
This issue is caused by reflection methods not existing in Java 9+, and they're pretty necessary to what we actually do with the mod. We'll try and make sure to keep hacky reflection shit to a minimum so as to keep compatibility with later versions of Java a possibility, but since we're finished with the 1.15.2 version of the mod, I don't know if we'll put out a fix for this, especially since the codebase is an absolute mess. I'm pretty sure macOS can still run any version of java, especially if it's an OpenJDK distribution, so you can try downloading the latest version of [AdoptOpenJDK 8 Hotspot](https://adoptopenjdk.net/releases.html?variant=openjdk8&jvmVariant=hotspot).

**Comment by ShadewEnder** [comment] 2021-01-02 11:18
> This is an issue when running natively on Apple Silicon which only has java 11+ built. I got the following crash, this was the only mod causing issues for me playing Valhesia.
> 
> https://pastebin.com/mNDLL9pV

@tkreind You can add these JVM flags if that's possible for you, it should fix the most problems:
```
--add-opens java.base/jdk.internal.reflect=ALL-UNNAMED
```

**Comment by Jonathing** [comment] 2021-10-31 06:30
Closing. 1.17 uses Java 16 :wheeze:

**Closed by Jonathing** 2021-10-31 06:30 UTC
Labels: Confirmed Issue, Help Wanted, Discussion, Important, Java 9+
