### ISSUE TITLE
The Midnight Error 

### ISSUE THREAD

**Issue by heiseshuishan** [Cryptic-Mushroom/The-Midnight#347] opened 2020-02-03 12:10 UTC
https://paste.ubuntu.com/p/gxQtZQSQHt/

**Comment by NLBlacky** [comment] 2020-02-16 12:48
Having the same error spammed in our console. This is with version _themidnight-0.3.5.jar_ on a server running the modpack MC Eternal version 1.3.2.

**Comment by catchra** [comment] 2020-02-26 00:23
i was afk and VanillaFix pop up and said The Midnight crashed and gave me this link [https://paste.dimdev.org/yayemovomu.mccrash](url)

**Comment by pixelblob** [comment] 2020-03-26 15:07
same problem here

**Comment by Jonathing** [comment] 2020-03-26 15:09
This issue seems to be for 1.12.2. As stated on the CurseForge page, we will no longer be updating the version for that version of Minecraft. I will try to see if the problem can be reproduced in the latest version for 1.15.2. If not, I will close this issue.

**Comment by Jonathing** [comment] 2020-03-26 15:12
The pastebins that were originally attached to the issue are no longer visible, so I will be closing this issue.

**Closed** 2020-03-26 15:12 UTC
Labels: 1.12.2, Won't Fix
