### ISSUE TITLE
Shaders with optifine do not work

### ISSUE THREAD

**Issue by canteloupeSamurai** [Cryptic-Mushroom/The-Midnight#337] opened 2020-01-10 01:00 UTC
If i remove shader's it works but not with them on, it would be nice to be able to have shaders on.

![image](https://user-images.githubusercontent.com/49422266/72117164-ae9e5600-331a-11ea-8435-1ce5fb3c24fc.png)

**Comment by nodogsleft** [comment] 2020-03-15 22:05
Same issue here. All textures appear black in Sildur's Vibrant, while CYBOX seems to load. (1.14.4)

![2020-03-15_17 01 48](https://user-images.githubusercontent.com/61568402/76711520-e0e37f80-66de-11ea-908e-f0f945ee2430.png)
![2020-03-15_17 03 02](https://user-images.githubusercontent.com/61568402/76711521-e17c1600-66de-11ea-9daf-54cf60772834.png)

**Comment by Jonathing** [comment] 2020-05-02 16:18
To be real, I don't think shaders with this version of The Midnight is going to be fixed anytime soon. The skybox is too dark and you really aren't meant to be playing this mod with shaders. Maybe in later versions we can fix this, but as of right now it's not a top priority because of how cumbersome it is to get them to work. I'll leave this issue open until we eventually drop support for 1.14.4 just so everyone knows that this is still an issue, but we most likely won't be fixing it.

**Comment by Jonathing** [comment] 2020-05-24 04:53
We as a team have confirmed that we *will not* be adding support for any shaders for 1.14.4 or in any future update. If shaders work at all in The Midnight, it is by pure chance.

**Closed by Jonathing** 2020-05-24 04:53 UTC
Labels: 1.14.4, Confirmed Issue, Mod Compatability, Won't Fix
